######################################################################
# Automatically generated by qmake (3.0) ?? 6? 21 16:35:46 2016
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

INCLUDEPATH += $$PWD/../include

LIBS += -L$$PWD/../bin/debug -lTMathd

# Input
SOURCES += main.cpp
